project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll
  render:
    - index.qmd
    - 01_intro_options.qmd
    - 02_intro_futures.qmd
    - 03_binomial_trees.qmd

execute:
  jupyter: python3

jupyter:
  kernel: python3

engine: jupyter

comments:
  hypothesis: true
