project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll
  render:
    - index.qmd
    - 01_intro_options.qmd

execute:
  jupyter: python3

jupyter:
  kernel: python3

engine: jupyter
